/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:ab7fc7b5-b403-4a93-9dd9-5baf480f4176",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_FWyuuZIwV",
    "aws_user_pools_web_client_id": "7h1l7fphfmtuq5ha8m0mhbbtqv",
    "oauth": {},
    "aws_user_files_s3_bucket": "querypal-bucket101108-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1",
    "aws_content_delivery_bucket": "querypal-20201223154123-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://querypal-20201223154123-hostingbucket-dev.s3-website-eu-west-1.amazonaws.com"
};


export default awsmobile;
